/* ======================================================
   STAGE 4 — Collection Customer Onboarding (9 emails / 21 days)
   Entrepreneurship & AI Collection · $399 · 31 programs
   Core 5: Amplify with AI, Superbrain, Everyday Bliss, Becoming Focused, Money EQ
   ====================================================== */

Object.assign(window.EMAIL_DATA, {

'co-1': {
    subject: "You're in! Welcome to the Entrepreneurship & AI Collection",
    preheader: '31 programs. 5 core quests. Your login is inside.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1920x1080/c62086ce77/ai_questcover_1920x1080_en.webp',
    schwartz: 'Most-Aware', cialdini: 'Commitment',
    cta: 'Log In & Explore \u2192', url: 'https://www.mindvalley.com/entrepreneur-collection',
    body: "Congratulations. You just made a decision that separates the top 1% of entrepreneurs from everyone else.\n\nYou did not buy a course. **You invested in an operating system upgrade for your brain, your business, and your life.**\n\nThe Entrepreneurship & AI Collection is now live in your account. Let me walk you through exactly what you have.\n\n---\n\n**What You Now Have Access To:**\n\n--> **31 transformational programs** spanning AI, productivity, mindset, focus, and wealth consciousness\n--> **5 flagship Quests** handpicked as your starting foundation\n--> **Hundreds of lessons** -- each designed for 15-20 minutes a day\n--> **New programs and updates** added to the collection over time\n\n---\n\n**Your 5 Core Quests:**\n\n--> **Amplify with AI** (Vishen Lakhiani) -- automate the busywork, reclaim 10+ hours/week\n--> **Superbrain** (Jim Kwik) -- upgrade memory, reading speed, and mental processing\n--> **Everyday Bliss** (Paul McKenna) -- build unshakeable calm under pressure\n--> **Becoming Focused** (Nir Eyal) -- eliminate distractions and execute with precision\n--> **Money EQ** (Ken Honda) -- transform your relationship with money at a deep level\n\nPlus 26 bonus programs covering everything from business strategy to negotiation to leadership.\n\n---\n\n**Where to Start:**\n\nMost members begin with one of two paths:\n\n--> **Amplify with AI** -- if you want immediate, tangible ROI. AI tools you can deploy this week.\n--> **Superbrain** -- if you want a foundational brain upgrade that makes everything else easier.\n\nBoth take about 15-20 minutes per day. Both deliver results within the first week.\n\nYour collection is waiting. Log in, pick your path, and press play.\n\n**[Log In & Explore \u2192](https://www.mindvalley.com/entrepreneur-collection)**\n\n---\n\nTo your upgraded operating system,\n\n[Signature]\n\nP.S. Tomorrow, I will show you how to take this entire collection with you everywhere -- in your pocket, on your commute, at the gym. The learning never has to stop."
},

'co-2': {
    subject: 'Download the app (learn anywhere, anytime)',
    preheader: 'Your commute, your workout, your walk -- all become growth time.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1920x1080/c62086ce77/ai_questcover_1920x1080_en.webp',
    schwartz: 'Most-Aware', cialdini: 'Commitment',
    cta: 'Download App \u2192', url: 'https://www.mindvalley.com/app',
    body: "The most successful entrepreneurs I know have one thing in common: **they turn dead time into growth time.**\n\nThe commute. The morning walk. The gym session. The 15 minutes before bed.\n\nWith the Mindvalley app, your entire Entrepreneurship & AI Collection travels with you.\n\n---\n\n**What the App Gives You:**\n\n--> **Stream or download lessons offline** -- no Wi-Fi needed. Perfect for flights, subways, and unplugged mornings.\n--> **Daily micro-lessons (15-20 min)** -- structured so you never have to wonder \"what should I learn today?\"\n--> **Progress tracking** -- see your streaks, completed lessons, and milestones at a glance.\n--> **Community access** -- connect with entrepreneurs from 195 countries who are on the same journey.\n\n---\n\n**How Top Members Use It:**\n\n--> Morning coffee + Amplify with AI lesson = start the day with an AI advantage\n--> Gym session + Superbrain audio = train your body AND your brain simultaneously\n--> Evening wind-down + Everyday Bliss = decompress and reprogram your stress response\n\nThe compound effect of learning during moments you would otherwise waste is staggering. 15 minutes a day becomes 91 hours of focused growth per year.\n\n---\n\n**Download now and your collection will sync automatically.**\n\n--> [iOS App Store](https://apps.apple.com/us/app/mindvalley-self-improvement/id1108786610)\n--> [Google Play Store](https://play.google.com/store/apps/details?id=com.mindvalley.mva)\n\n**[Download App \u2192](https://www.mindvalley.com/app)**\n\n---\n\nTo growth in every moment,\n\n[Signature]\n\nP.S. Tomorrow, I will help you decide exactly which quest to start first. A simple framework that takes 60 seconds and points you to the perfect starting point for where you are right now."
},

'co-3': {
    subject: 'Which quest should you start first? (take this 60-second quiz)',
    preheader: '5 paths. One is perfect for where you are right now.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1920x1080/c62086ce77/ai_questcover_1920x1080_en.webp',
    schwartz: 'Product-Aware', cialdini: 'Reciprocity',
    cta: 'Start Amplify with AI \u2192', url: 'https://www.mindvalley.com/entrepreneur-collection',
    body: "You have 31 programs at your fingertips. That is powerful -- but I do not want you staring at a menu when you could be transforming your business.\n\n**So here is a 60-second decision framework.**\n\nAnswer one question: **What is the single biggest bottleneck in your business or career right now?**\n\n---\n\n**If you need more TIME:**\n\n--> Start with **Amplify with AI** (Vishen Lakhiani)\n--> You are drowning in tasks that AI could handle. This quest shows you how to automate content creation, research, analysis, and decision-making. Most members reclaim 10+ hours in their first week.\n\n**If you want to THINK faster and learn more:**\n\n--> Start with **Superbrain** (Jim Kwik)\n--> Your brain is your ultimate business asset. Jim coaches Google, Nike, and SpaceX on memory, speed reading, and accelerated learning. Upgrade the hardware before loading new software.\n\n**If you are STRESSED and burning out:**\n\n--> Start with **Everyday Bliss** (Paul McKenna)\n--> You cannot build a great business from a shattered nervous system. Paul has helped 10 million people rewire their stress response. This is not relaxation -- it is performance-grade calm.\n\n**If you are DISTRACTED and cannot execute:**\n\n--> Start with **Becoming Focused** (Nir Eyal)\n--> Nir wrote the book on distraction (literally -- \"Indistractable\" is a Wall Street Journal bestseller). This quest gives you a proven system for deep work and follow-through.\n\n**If your relationship with MONEY is broken:**\n\n--> Start with **Money EQ** (Ken Honda)\n--> Ken is Japan's most influential money teacher. If money feels stressful, scarce, or complicated, this quest transforms the emotional relationship that drives every financial decision you make.\n\n---\n\n**Not sure? Start with Amplify with AI.**\n\nMost members do. It delivers the fastest visible results -- you will see AI saving you hours within the first three lessons. And that freed-up time creates space for everything else.\n\n**[Start Amplify with AI \u2192](https://www.mindvalley.com/entrepreneur-collection)**\n\n---\n\nTo your clearest path forward,\n\n[Signature]\n\nP.S. Whichever quest you choose, it takes only 15 minutes for your first lesson. Tomorrow, I will explain why those 15 minutes might be the most important quarter-hour of your week."
},

'co-4': {
    subject: '15 minutes that could change your business',
    preheader: 'The people who transform are not different. They just pressed play.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1920x1080/c62086ce77/ai_questcover_1920x1080_en.webp',
    schwartz: 'Product-Aware', cialdini: 'Commitment/Consistency',
    cta: 'Open App \u2192', url: 'https://www.mindvalley.com/app',
    body: "I have watched hundreds of thousands of entrepreneurs join Mindvalley over the years.\n\nThe ones who transform their businesses and their lives are not smarter, luckier, or more disciplined than the rest.\n\n**They did one thing differently: they did not wait for the perfect moment. They pressed play.**\n\n---\n\nYour first lesson takes about **15 minutes.**\n\nNot an hour. Not a weekend retreat. Not a 12-week bootcamp before you see results.\n\nFifteen minutes. While you drink your morning coffee. While you walk the dog. While you sit in the parking lot before a meeting.\n\n**That is 15 minutes to:**\n\n--> Begin rewiring how you approach your biggest business challenges\n--> Experience a world-class teacher guiding you step by step\n--> Feel the first subtle shift -- the one that tells you something is different\n\n---\n\n**Here is what most members report:**\n\nLesson 1: \"That was interesting.\"\nLesson 2: \"Okay, I see where this is going.\"\nLesson 3: **\"Wait -- this changes everything.\"**\n\nThe \"aha moment\" almost always lands within the first three lessons. But you have to start to feel it.\n\n---\n\n**The compound effect is real.**\n\n15 minutes a day for 21 days = 5.25 hours of focused entrepreneurial training from a world-class expert. That is more than most MBA students get in a month of relevant, actionable content.\n\nAnd unlike an MBA, you can implement what you learn the same day.\n\n---\n\nOpen the app. Press play. Your first lesson is waiting.\n\n**[Open App \u2192](https://www.mindvalley.com/app)**\n\n---\n\nRooting for you,\n\n[Signature]\n\nP.S. In two days, I will share the full 6-month roadmap for your collection -- the exact sequence our top-performing entrepreneur members follow. But first, get that first lesson done. Everything builds from here."
},

'co-5': {
    subject: 'The 5-pillar entrepreneur reset (your collection roadmap)',
    preheader: 'A 6-month operating system upgrade. Here is the exact sequence.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1920x1080/c62086ce77/ai_questcover_1920x1080_en.webp',
    schwartz: 'Product-Aware', cialdini: 'Authority',
    cta: 'Start Full Quest \u2192', url: 'https://www.mindvalley.com/entrepreneur-collection',
    body: "Most entrepreneurs approach personal development like a buffet -- a little of this, a little of that, no real sequence.\n\nThat is why most personal development does not stick.\n\n**What I am about to share is different.** This is the exact learning path our highest-performing entrepreneur members follow. It is designed as a system -- each pillar builds on the last.\n\n---\n\n**THE 5-PILLAR ENTREPRENEUR RESET**\n\n**Pillar 1 -- Weeks 1-3: Amplify with AI**\n--> Automate the busywork. Deploy AI for content, research, analysis, and decision support.\n--> **Result:** You reclaim 10-15 hours per week. This freed time funds everything that follows.\n\n**Pillar 2 -- Weeks 4-7: Superbrain**\n--> Upgrade your processing speed. Memory techniques, speed reading, accelerated learning.\n--> **Result:** You absorb information 2-3x faster. Every book, meeting, and conversation yields more.\n\n**Pillar 3 -- Weeks 8-10: Becoming Focused**\n--> Eliminate distractions. Build an environment and system designed for deep work.\n--> **Result:** Your execution speed doubles. Projects that took months start finishing in weeks.\n\n**Pillar 4 -- Weeks 11-13: Everyday Bliss**\n--> Build unshakeable calm. Rewire your stress response at the neurological level.\n--> **Result:** High-pressure situations become opportunities. You make better decisions under fire.\n\n**Pillar 5 -- Weeks 14-16: Money EQ**\n--> Transform your relationship with money. Dissolve the emotional blocks around wealth.\n--> **Result:** Financial decisions come from clarity, not fear. Pricing, investing, and earning shift permanently.\n\n---\n\n**After the Core 5 -- Months 4-6:**\n\nExplore the 26 bonus programs. Business Freedom Blueprint by Eric Edmeades. Zero to $100 Million by Miki Agrawal. Vivid Vision by Cameron Herold. Leadership. Negotiation. Communication. Public speaking.\n\nThink of the first 16 weeks as building the foundation. Months 4-6 are building the house.\n\n---\n\n**This is a 6-month operating system upgrade.**\n\nNot a weekend hack. Not a motivational boost that fades by Tuesday. A systematic reconstruction of how you think, work, earn, focus, and lead.\n\nStart Pillar 1 today.\n\n**[Start Full Quest \u2192](https://www.mindvalley.com/entrepreneur-collection)**\n\n---\n\nTo your complete transformation,\n\n[Signature]\n\nP.S. Bookmark this email. Seriously. You will want to come back to this roadmap as you progress through each pillar. In two days, I will check in on your Week 1 progress."
},

'co-6': {
    subject: "Week 1 done -- what's shifting for you?",
    preheader: 'Something is already different. Here is what other members experience.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1920x1080/c62086ce77/ai_questcover_1920x1080_en.webp',
    schwartz: 'Product-Aware', cialdini: 'Social Proof',
    cta: 'Continue Quest \u2192', url: 'https://www.mindvalley.com/entrepreneur-collection',
    body: "One week.\n\nSeven days since you stepped into the Entrepreneurship & AI Collection. Whether you have completed seven lessons or you are just finding your rhythm -- **something has already shifted.**\n\nThe simple act of committing to daily learning changes how your brain processes opportunity. You are already different from the version of you seven days ago.\n\n---\n\n**What Other Members Typically Experience by Week 1:**\n\n--> **Faster decision-making.** The frameworks you are absorbing start running in the background. Decisions that used to take days start resolving in hours.\n--> **3-5 hours saved with AI.** If you started Amplify with AI, you have likely already deployed at least one tool that is handling work you used to do manually.\n--> **30% faster reading and information processing.** If you started Superbrain, Jim Kwik's techniques compound fast. Your brain is already rewiring.\n--> **A new awareness of distractions.** If you started Becoming Focused, you are noticing patterns you never saw before -- and that awareness alone is powerful.\n\nThese are not extraordinary results. **These are typical Week 1 outcomes.** The extraordinary results come after Week 2.\n\n---\n\n**Why Week 2 Matters More Than Week 1:**\n\nNeuroscience shows that new neural pathways begin to solidify after 7-14 days of consistent practice. What felt like effort in Week 1 starts becoming automatic in Week 2.\n\nThis is where the compound effect kicks in.\n\nA habit that takes willpower today becomes effortless by Day 14. And an effortless habit practiced for 21 days becomes part of who you are.\n\n---\n\n**So keep going.**\n\n15 minutes today. That is all. Not a heroic effort -- just consistency.\n\nThe members who see the biggest transformations are not the fastest learners. They are the most consistent. One lesson a day. Every day. That is the entire formula.\n\n**[Continue Quest \u2192](https://www.mindvalley.com/entrepreneur-collection)**\n\n---\n\nProud of you for being here,\n\n[Signature]\n\nP.S. In three days, I will introduce you to some hidden gems inside your collection that most members do not discover until month 2. These bonus programs are not filler -- they are full-scale business tools worth hundreds each."
},

'co-7': {
    subject: 'Unlock the AI Tools Library inside your collection',
    preheader: 'Beyond the core 5 -- these bonus programs are worth $199-$599 each.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1920x1080/c62086ce77/ai_questcover_1920x1080_en.webp',
    schwartz: 'Product-Aware', cialdini: 'Reciprocity',
    cta: 'Explore Tools \u2192', url: 'https://www.mindvalley.com/entrepreneur-collection',
    body: "Quick question: **have you explored the 26 bonus programs yet?**\n\nMost members spend the first week or two focused on their core quest -- which is exactly right. But there is a library sitting inside your collection that most people do not discover until later.\n\nI do not want you to be one of those people. Because some of these programs are game-changers on their own.\n\n---\n\n**3 Bonus Programs Every Entrepreneur Should Know About:**\n\n**1. Business Freedom Blueprint** (Eric Edmeades)\n--> Eric built and sold multiple companies before age 40. This program reverse-engineers the exact systems that let entrepreneurs scale without sacrificing their health, relationships, or sanity.\n--> **Individual value: $399.** Included in your collection.\n\n**2. Zero to $100 Million** (Miki Agrawal)\n--> Miki built three companies from zero to $100M+, including THINX and TUSHY. This is not theory -- it is a founder's playbook for scaling fast, raising capital, and building brands that dominate categories.\n--> **Individual value: $499.** Included in your collection.\n\n**3. Vivid Vision** (Cameron Herold)\n--> Cameron is the \"CEO Whisperer\" who scaled 1-800-GOT-JUNK from $2M to $106M in 6 years. Vivid Vision teaches you to create a 3-year vision so clear that your team, investors, and customers can see it too.\n--> **Individual value: $199.** Included in your collection.\n\n---\n\n**These are not filler programs.** They are full-scale courses from entrepreneurs who have built and scaled real businesses to real exits.\n\nThe combined individual value of these three alone is over $1,000. You have them all.\n\n---\n\n**How to use them:**\n\nDo not interrupt your current quest. Finish your core program first.\n\nBut open the collection and browse. Bookmark the ones that speak to your current challenges. When you finish your first quest, you will know exactly where to go next.\n\n**[Explore Tools \u2192](https://www.mindvalley.com/entrepreneur-collection)**\n\n---\n\nTo your expanding toolkit,\n\n[Signature]\n\nP.S. In four days, I will share stories from three entrepreneurs who used this collection to produce specific, measurable results. Revenue numbers. Hours saved. Businesses launched. Real data from real people."
},

'co-8': {
    subject: 'What 3 entrepreneurs did with this collection (results inside)',
    preheader: 'Revenue growth, time saved, businesses launched -- real stories.',
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1920x1080/c62086ce77/ai_questcover_1920x1080_en.webp',
    schwartz: 'Product-Aware', cialdini: 'Social Proof',
    cta: 'Explore Collection \u2192', url: 'https://www.mindvalley.com/entrepreneur-collection',
    body: "I want to share something today -- not from me, but from three entrepreneurs who are working through the same collection you have.\n\nThese are not motivational stories. These are specific, measurable results.\n\n---\n\n**JASON, 36, CHICAGO** -- SaaS founder, team of 12.\n\nStarted with Amplify with AI. Within two weeks, he had deployed AI agents for customer support triage, content drafting, and competitive analysis. His team reclaimed 22 hours per week collectively.\n\nThen Superbrain. His meeting notes went from scattered to photographic. He stopped needing to re-read reports. Reading speed doubled.\n\n**6-month result: Revenue up 45%. Reduced team workload by 30%. Says his \"brain feels 10 years younger.\"**\n\n---\n\n**AMANDA, 43, TORONTO** -- Marketing consultant, solo practitioner.\n\nStarted with Becoming Focused. She had been working 60-hour weeks and still falling behind. Nir Eyal's system helped her identify that she was losing 3 hours a day to reactive tasks disguised as urgent work.\n\nThen Everyday Bliss. The stress that had been driving those 60-hour weeks dissolved. She started making decisions from calm clarity instead of cortisol-fueled panic.\n\n**6-month result: Cut working hours from 60 to 38 per week. Revenue actually increased 20% because she was executing on the right things. Blood pressure dropped from borderline high to normal.**\n\n---\n\n**OMAR, 29, DUBAI** -- E-commerce entrepreneur, just launched.\n\nStarted with Money EQ. He had $180K in savings but could not bring himself to invest in his business. Ken Honda's work revealed a deep fear of losing money inherited from his father.\n\nThen Amplify with AI to build his marketing engine, and Vivid Vision to create a crystal-clear 3-year plan.\n\n**6-month result: Launched his store, hit $40K/month revenue by month 5. Invested $50K in inventory without the old paralysis. Says Money EQ was \"the key that unlocked everything else.\"**\n\n---\n\nThree different starting points. Three different businesses. Same collection. Same 15 minutes a day.\n\nYou are on the same path they walked. Keep going.\n\n**[Explore Collection \u2192](https://www.mindvalley.com/entrepreneur-collection)**\n\n---\n\nTo your story being written right now,\n\n[Signature]\n\nP.S. In one week, we hit the 3-week milestone. I will have something special for you then -- a checkpoint that will help you see exactly how far you have come and where the next breakthrough lives."
},

'co-9': {
    subject: "21 days in -- here's what most members do next",
    preheader: "3-week milestone. Here is what you have built and what is ahead.",
    img: 'https://storyblok-cdn.mindvalley.com/f/60579/1920x1080/c62086ce77/ai_questcover_1920x1080_en.webp',
    schwartz: 'Most-Aware', cialdini: 'Commitment/Consistency',
    cta: 'Continue Journey \u2192', url: 'https://www.mindvalley.com/entrepreneur-collection',
    body: "Three weeks ago, you made a decision that most entrepreneurs never make.\n\nNot just to buy a program -- but to systematically upgrade how you think, work, learn, focus, and earn. To treat personal transformation as a business strategy, not a nice-to-have.\n\n**Let me acknowledge that.**\n\n---\n\n**What You Have Built in 21 Days:**\n\n--> A daily learning habit that is becoming automatic\n--> New frameworks running in the background of every decision you make\n--> At least one quest completed or well underway\n--> Tangible results -- hours saved, focus improved, stress reduced, or money mindset shifted\n\nWhether you have been consistent every single day or you have had some gaps -- **you are in a fundamentally different place than you were 21 days ago.** The neural pathways are forming. The compound effect is building.\n\n---\n\n**What Most Members Do at This Point:**\n\nIf you have completed your first quest -- congratulations. You are ahead of 80% of people who buy online programs.\n\nHere is what the highest-performing members do next:\n\n--> **Start Quest 2.** Look at the 5-Pillar Roadmap from my Day 5 email. Which pillar is next? Begin that quest this week.\n--> **Layer in bonus programs.** Browse the 26 extras. Find one that addresses your most pressing business challenge right now.\n--> **Keep the streak alive.** The difference between people who transform and people who learn-and-forget is simple: they kept going past Day 21.\n\n---\n\n**Your Full Roadmap (reminder):**\n\n--> Weeks 1-3: Amplify with AI (automate the busywork)\n--> Weeks 4-7: Superbrain (upgrade processing speed)\n--> Weeks 8-10: Becoming Focused (eliminate distractions)\n--> Weeks 11-13: Everyday Bliss (build unshakeable calm)\n--> Weeks 14-16: Money EQ (transform money relationship)\n--> Months 4-6: 26 bonus programs (build the house)\n\nYou are 3 weeks in. The foundation is laid. Now the real building begins.\n\n---\n\nI want to share one more thing.\n\nMany members at this point start noticing something: their growth does not want to stay in one lane. You came for business skills. But now you are curious about health, relationships, leadership, creativity, spiritual growth.\n\nThat is not a distraction. **That is a signal.**\n\nThe entrepreneurs who build truly extraordinary lives do not just optimize their businesses. They optimize themselves -- across every dimension.\n\nKeep that thought in mind. I will have more to share on this soon.\n\n**[Continue Journey \u2192](https://www.mindvalley.com/entrepreneur-collection)**\n\n---\n\nWith deep respect for how far you have come,\n\n[Signature]\n\nP.S. You started with 31 programs. But what if you had access to 100+? Programs on health, longevity, relationships, speaking, leadership, and more? Many members at your stage start exploring that possibility. Stay tuned."
}

});
