/* ======================================================
   STAGE 3 — Collection Customer Onboarding (9 emails / 21 days)
   Entrepreneurship & AI Collection
   Quality upgrade v3: richer copy, images, stories per email
   BJ Fogg (B=MAP) + Nir Eyal (Hook Model)
   ONE action per email. Reduce choice to one.
   ====================================================== */

Object.assign(window.EMAIL_DATA, {

'co-1': {
    subject: "you're in -- here's your one next step",
    preheader: 'Not 31 programs. Just one button.',
    img: '',
    schwartz: 'Most-Aware', cialdini: 'Commitment',
    cta: 'Start Lesson 1', url: 'https://www.mindvalley.com/membership/quests/amplify-with-ai',
    body: "# Welcome to the Exponential Entrepreneur Collection\n\n[Placeholder for Exponential Entrepreneurship collection banner]\n\nYou just made a decision most people only talk about.\n\nYour collection is live. Five core quests — Amplify with AI, Superbrain, Everyday Bliss, Becoming Focused, and Money EQ. Bonus programs. A full entrepreneurial operating system designed to transform not just your business, but how you think, focus, handle stress, and relate to money.\n\nBut right now, none of that matters.\n\nRight now, only one thing matters: **your first lesson.**\n\nWe have already queued it up for you. It is Lesson 1 of **Amplify with AI** with Vishen Lakhiani — the quest most members start with because it delivers visible results fastest. In 15 minutes, you will learn the ACE Communication Method — a framework that permanently changes how you interact with AI.\n\nDo not browse. Do not plan. Do not organize.\n\nJust open the app and press play.\n\n{{STORY}}\nhttps://res.cloudinary.com/mindvalley/image/fetch/f_auto,q_auto,w_400,h_400,c_fill,dpr_1.7/https://storage.googleapis.com/mv-stories/34851/8-Foto.jpg\n**\\\"I now use AI daily for problem-solving, learning, and business planning\\\"**\nNestor Hernandez, Entrepreneur, Bogota, Colombia\n\n{{STORY}}\nhttps://res.cloudinary.com/mindvalley/image/fetch/f_auto,q_auto,w_400,h_400,c_fill,dpr_1.7/https://storage.googleapis.com/mv-stories/34713/Screenshot%202025-08-24%20at%2010.33.04%E2%80%AFAM.png\n**\\\"I feel powerful, super productive, able to work 4 things simultaneously\\\"**\nMarcela Diaz, General Manager, San Jose, Costa Rica\n\n**[Start Lesson 1](https://www.mindvalley.com/membership/quests/amplify-with-ai)**\n\nThat is it. That is your entire job today.\n\nTomorrow we will talk about turning this into a habit that sticks.\n\nThe Mindvalley Team\n\nP.S. The entrepreneurs who transform fastest are the ones who start the same day they sign up. Fifteen minutes. One lesson. Today."
},

'co-2': {
    subject: 'the morning coffee trick',
    preheader: 'How to make 15 minutes of learning automatic.',
    img: '',
    schwartz: 'Most-Aware', cialdini: 'Commitment',
    cta: 'Download the App', url: 'https://www.mindvalley.com/app',
    body: "# Your Mindvalley Moment\n\nHere is a question that sounds simple but changes everything:\n\n**When in your day do 15 minutes already exist?**\n\nAfter your morning coffee? During your commute? Right before bed when you are scrolling anyway?\n\nThat window is your Mindvalley Moment.\n\nThe members who transform are not the ones with the most willpower. They are the ones who **attached learning to something they already do.**\n\nCoffee brews. You open the app. You press play. Fifteen minutes later, you have done more for your business than most people do in a week of podcasts and YouTube rabbit holes.\n\n---\n\nBehavior scientist BJ Fogg calls this \"habit stacking\" — attaching a new behavior to an existing routine. The existing routine is the trigger. The new behavior rides on its momentum. No willpower required.\n\nThe trick is having the app on your phone so the friction is zero. One screen tap instead of a scroll.\n\nDownload it now. Your collection syncs automatically. Tomorrow morning, when you reach for your phone out of habit — Amplify with AI will be right there waiting.\n\n{{STORY}}\nhttps://res.cloudinary.com/mindvalley/image/fetch/f_auto,q_auto,w_400,h_400,c_fill,dpr_1.7/https://storage.googleapis.com/mv-stories/34523/Riviere%20on%20stage.png\n**\\\"From my work, health, love to growth it's made my job better\\\"**\nKeir Dixon, Music Therapist, Vancouver, Canada\n\n**[Download the App](https://www.mindvalley.com/app)**\n\nThe Mindvalley Team\n\nP.S. Already downloaded? Good. Open it right now and finish today's lesson. The streak starts today."
},

'co-3': {
    subject: 'lesson 2 is the one that hooks people',
    preheader: 'You picked your quest. Now the momentum builds.',
    img: '',
    schwartz: 'Product-Aware', cialdini: 'Commitment',
    cta: 'Open Lesson 2', url: 'https://www.mindvalley.com/app',
    body: "# The One That Changes the Conversation\n\nYou started Amplify with AI. That was the right call.\n\nHere is what is coming next: Lesson 2 is where Vishen introduces **Computational Thinking** — the mental model that transforms how you see your entire workflow. Not theory. Not philosophy. A framework you will use to identify exactly which parts of your work AI should handle — and which parts need you.\n\nMembers consistently say Lesson 2 is where it clicks — where \"this is interesting\" turns into \"wait, this changes how I work.\"\n\nYou already did the hard part. You showed up for Lesson 1.\n\nLesson 2 is just 15 more minutes. Same routine. Same coffee. Same spot.\n\n{{STORY}}\nhttps://res.cloudinary.com/mindvalley/image/fetch/f_auto,q_auto,w_400,h_400,c_fill,dpr_1.7/https://storage.googleapis.com/mv-stories/34243/1751177955281.jpg\n**\\\"This course helped me realize my music can be amplified with more clarity and impact\\\"**\nNuchanat Kraprayoon, Actor, Bangkok, Thailand\n\n**[Open Lesson 2](https://www.mindvalley.com/app)**\n\nYou do not need to rethink your quest. You do not need to explore other programs. You are exactly where you should be.\n\nKeep going.\n\nThe Mindvalley Team"
},

'co-4': {
    subject: 'she saved 11 hours in her first week',
    preheader: 'A real founder. A real week. A real result.',
    img: '',
    schwartz: 'Product-Aware', cialdini: 'Social Proof',
    cta: 'Continue Your Quest', url: 'https://www.mindvalley.com/app',
    body: "# 11 Hours Back\n\nSara runs a 7-person marketing agency in Melbourne.\n\nWhen she started Amplify with AI, she was working 55-hour weeks and falling behind on client deliverables. Her mornings started with a pit in her stomach — too many tasks, not enough hours.\n\nShe did her first lesson on a Tuesday morning while her coffee brewed.\n\nBy Friday, she had used what Vishen taught to automate her client research briefs — a task that used to eat 2 hours per client. She had five clients that week.\n\nEleven hours. Back. In five days.\n\nShe did not change her schedule. She did not hire anyone. She did not grind harder. She just opened the app, learned one thing, and applied it.\n\n---\n\nThat is what 15 minutes a day can compound into.\n\nAnd it is not just about AI. The collection works as a system. Each program strengthens a different lever of your entrepreneurial operating system.\n\nHere are three entrepreneurs who activated different levers:\n\n{{STORY}}\nhttps://res.cloudinary.com/mindvalley/image/fetch/f_auto,q_auto,w_400,h_400,c_fill,dpr_1.7/https://storage.googleapis.com/mv-stories/15388/wechatimg3600.jpeg\n**\\\"I doubled my revenue and I reimbursed 11,000 USD of debt in one year\\\"**\nAudrey Tournier, Founder of Slow Living, Shenzhen, China\n\n{{STORY}}\nhttps://res.cloudinary.com/mindvalley/image/fetch/f_auto,q_auto,w_400,h_400,c_fill,dpr_1.7/https://storage.googleapis.com/mv-stories/28331/IMG_0625_jpg.jpg\n**\\\"I've reached a point where I can navigate my days without being pulled away by social media\\\"**\nErik Solg, Computer Systems Engineer, Tallinn, Estonia\n\n{{STORY}}\nhttps://res.cloudinary.com/mindvalley/image/fetch/f_auto,q_auto,w_400,h_400,c_fill,dpr_1.7/https://storage.googleapis.com/mv-stories/33127/photo_2024-05-16_17-26-40.jpg\n**\\\"Happy for no particular reason, my usual state now\\\"**\nAnastasia, Athens, Greece\n\nYour version of Sara's 11 hours is sitting inside your next lesson.\n\n**[Continue Your Quest](https://www.mindvalley.com/app)**\n\nThe Mindvalley Team\n\nP.S. Sara did not know she would save 11 hours when she pressed play. She just showed up. The compound effect did the rest."
},

'co-5': {
    subject: 'what gets sequenced gets done',
    preheader: 'Your quest knows the order. You just show up.',
    img: '',
    schwartz: 'Product-Aware', cialdini: 'Authority',
    cta: 'Open Today\'s Lesson', url: 'https://www.mindvalley.com/app',
    body: "# The Order Is Already Handled\n\nHere is something most people do not realize about Mindvalley quests:\n\n**The sequencing is the product.**\n\nVishen did not just record lessons and toss them in a folder. Each lesson was designed to land *after* the previous one rewired something specific. Lesson 3 only works because Lesson 2 shifted how you see the problem. Lesson 5 builds on the tool you deployed in Lesson 4.\n\nThis is not a content library. It is a transformation architecture. The order matters as much as the content.\n\n---\n\nYou do not need to plan what to learn next. You do not need to skip ahead to the \"good part.\" The good part is always the next lesson in line.\n\nWhat gets sequenced gets done. And this sequence was built by someone who used AI to cut his own company's workload by 90%.\n\nYour only job: open the app, press play on whatever lesson is next.\n\nThat is it. The quest handles the rest.\n\n{{STORY}}\nhttps://res.cloudinary.com/mindvalley/image/fetch/f_auto,q_auto,w_400,h_400,c_fill,dpr_1.7/https://storage.googleapis.com/mv-stories/34388/Screenshot%202025-07-10%20at%2011.23.42.png\n**\\\"I didn't just learn new prompts--I learned to lead with purpose\\\"**\nManon Doucet, Self-employed, Ottawa, Canada\n\n**[Open Today's Lesson](https://www.mindvalley.com/app)**\n\nThe Mindvalley Team\n\nP.S. You are almost a week in. Something is already shifting in how you think about your work. Trust that."
},

'co-6': {
    subject: 'still here?',
    preheader: 'The program is still here. So is the version of you that signed up.',
    img: '',
    schwartz: 'Product-Aware', cialdini: 'Commitment',
    cta: 'Pick Up Where You Left Off', url: 'https://www.mindvalley.com/app',
    body: "# One Week\n\nSeven days since you joined.\n\nIf you have been showing up daily — this email is a high five. You are doing the thing. The neural pathways are forming. The habit is taking root. Keep going and skip to the button below.\n\nIf life got in the way and you have not opened the app in a few days — this email is a gentle tap on the shoulder.\n\nNo guilt. No motivational speech. Just a fact:\n\n**The program is still here. So is the version of you that signed up.**\n\nThat version of you saw something. A future where work felt lighter, where AI handled the grind, where 15 minutes a day compounded into a fundamentally different business.\n\nThat future has not expired. Your quest is paused exactly where you left it.\n\n---\n\nOne tap. Fifteen minutes. Today.\n\nNot tomorrow. Not Monday. Not \"when things calm down.\" Things never calm down. You know that.\n\n{{STORY}}\nhttps://res.cloudinary.com/mindvalley/image/fetch/f_auto,q_auto,w_400,h_400,c_fill,dpr_1.7/https://storage.googleapis.com/mv-stories/34614/0412dca4901f9a338051421be0eab715.png\n**\\\"AI is now my cofounder and muse\\\"**\nJeana Gwyn, Entrepreneur, Largo, United States\n\n{{STORY}}\nhttps://res.cloudinary.com/mindvalley/image/fetch/f_auto,q_auto,w_400,h_400,c_fill,dpr_1.7/https://storage.googleapis.com/mv-stories/21976/maria-lains-kuriakostv-2640_websize.jpg\n**\\\"Now all areas of my life are in my calendar which makes me feel in control of my own life\\\"**\nMaria Lains, Nutritionist, Lisbon, Portugal\n\n**[Pick Up Where You Left Off](https://www.mindvalley.com/app)**\n\nWe are not going anywhere. Neither is your potential.\n\nThe Mindvalley Team"
},

'co-7': {
    subject: 'you have earned the right to go deeper',
    preheader: 'Your collection has layers. Here is the next one.',
    img: '',
    schwartz: 'Product-Aware', cialdini: 'Reciprocity',
    cta: 'Explore Your Collection', url: 'https://www.mindvalley.com/membership/quests',
    body: "# The Next Layer\n\nYou have been showing up. Lessons done. Habits forming. AI tools deployed or focus sharpened or stress dissolving — whatever your quest is building, it is building.\n\nNow here is something you have earned: **a wider view.**\n\nYour collection is not just Amplify with AI. Sitting behind your current quest are four more core programs — each one strengthening a different lever of your entrepreneurial operating system:\n\n→ **Superbrain** (Jim Kwik) — Process information faster, remember everything, learn at 2-3x speed\n→ **Everyday Bliss** (Paul McKenna) — Eliminate stress at the source, not manage it\n→ **Becoming Focused** (Nir Eyal) — Kill distractions, execute with precision\n→ **Money EQ** (Ken Honda) — Transform your emotional relationship with money\n\nPlus bonus programs from founders who have scaled to 8 and 9 figures.\n\n---\n\nYou do not need to start them now. But you have earned the right to browse.\n\nOpen your collection. Look at what is next. Let curiosity pull you forward instead of obligation pushing you.\n\nWhen you finish your current quest, you will already know where you are headed. And that anticipation — that pull toward the next transformation — is what separates people who buy programs from people who build entrepreneurial operating systems.\n\n{{STORY}}\nhttps://res.cloudinary.com/mindvalley/image/fetch/f_auto,q_auto,w_400,h_400,c_fill,dpr_1.7/https://storage.googleapis.com/mv-stories/34451/SEL%20Insight.JPG\n**\\\"Practical, down-to-earth ways to incorporate AI into work and life\\\"**\nSantiago Echeverri Lopera, Business Unit Manager, Valencia, Spain\n\n**[Explore Your Collection](https://www.mindvalley.com/membership/quests)**\n\nFinish your current quest first. But know that the depth goes further than you think.\n\nThe Mindvalley Team"
},

'co-8': {
    subject: 'the founder who almost quit on day 4',
    preheader: 'His name is Marco. Here is what happened next.',
    img: '',
    schwartz: 'Product-Aware', cialdini: 'Social Proof',
    cta: 'Continue Your Quest', url: 'https://www.mindvalley.com/app',
    body: "# Marco Almost Quit\n\nMarco Pellegrini, 41, runs a logistics company in Milan. Twelve employees. Growing fast but grinding harder.\n\nHe bought the Entrepreneurship Collection on a late-night impulse. Did Lesson 1 of Amplify with AI. Interesting. Did Lesson 2. Useful. Lesson 3 — got interrupted by a client fire. Day 4, he did not open the app.\n\nDay 5, he almost wrote it off. \"Another course I bought and did not finish.\"\n\nBut his wife had noticed something. \"You were calmer those three days,\" she said. \"You talked about work differently.\"\n\n---\n\nSo he opened the app. Did Lesson 4. Then 5. By Lesson 8, he had automated his entire invoicing workflow with AI. By Lesson 15, his team was using AI for route optimization — saving 14 hours of manual scheduling per week.\n\nSix months later, Marco's company grew 32% with the same headcount. He works 40-hour weeks instead of 60. He finished three quests total.\n\nThe only difference between Marco's \"another abandoned course\" and Marco's 32% growth was one decision on Day 5: open the app.\n\nHere are entrepreneurs who made the same decision:\n\n{{STORY}}\nhttps://res.cloudinary.com/mindvalley/image/fetch/f_auto,q_auto,w_400,h_400,c_fill,dpr_1.7/https://storage.googleapis.com/mv-stories/34476/DSC_4874.jpg\n**\\\"I am truly excited about the countless ways AI can enhance my life\\\"**\nNilkanth Jatar, Sales Director, Pune, India\n\n{{STORY}}\nhttps://res.cloudinary.com/mindvalley/image/fetch/f_auto,q_auto,w_400,h_400,c_fill,dpr_1.7/https://storage.googleapis.com/mv-stories/34338/Pat%202025-06-24%20074404.png\n**\\\"Everything I've been doing can be taken up a notch\\\"**\nPat Costello, Business Management Analyst, Oceanside, United States\n\n{{STORY}}\nhttps://res.cloudinary.com/mindvalley/image/fetch/f_auto,q_auto,w_400,h_400,c_fill,dpr_1.7/https://storage.googleapis.com/mv-stories/21359/Winterland.jpg\n**\\\"My financial life has changed dramatically\\\"**\nSilvia Estevez, Salt Lake City, United States\n\n**[Continue Your Quest](https://www.mindvalley.com/app)**\n\nYour Day 5 moment might be today. Or it might have already passed. Either way — the app is one tap away.\n\nThe Mindvalley Team\n\nP.S. Marco says the hardest part was not the program. It was reopening the app after he stopped. \"Once I did, it was easy again.\" If you have paused — this is your tap on the shoulder."
},

'co-9': {
    subject: 'you are not the same person who signed up 21 days ago',
    preheader: 'Something has shifted. Let us name it.',
    img: '',
    schwartz: 'Most-Aware', cialdini: 'Commitment',
    cta: 'Keep Building', url: 'https://www.mindvalley.com/app',
    body: "# The Shift\n\nTwenty-one days ago, you bought a collection of programs.\n\nToday, you are someone who learns daily. Someone who reaches for the app instead of the scroll. Someone who has started to see AI, focus, and business through a fundamentally different lens.\n\nThat is not a small thing. That is an identity shift.\n\n---\n\nYou are no longer someone who bought a program. You are someone who is **building an entrepreneurial operating system** — one lesson, one habit, one compounding day at a time.\n\nAnd here is what makes stopping feel wrong now: you can feel the momentum. The way decisions come faster. The way your relationship with work has changed. The way you notice things — patterns, opportunities, inefficiencies — that you were blind to three weeks ago.\n\nThat momentum is not fragile. But it does need to be fed.\n\nYour next quest is waiting. Your collection goes deeper than you have explored. The version of you at Day 42 will look back at Day 21 the way Day 21 you looks back at Day 0 — and wonder how you ever operated without this.\n\nHere are people who kept going past Day 21:\n\n{{STORY}}\nhttps://res.cloudinary.com/mindvalley/image/fetch/f_auto,q_auto,w_400,h_400,c_fill,dpr_1.7/https://storage.googleapis.com/mv-stories/34477/ChatGPT%20Image%20Jul%2021,%202025,%2009_01_42%20PM.png\n**\\\"I stopped learning passively and started building\\\"**\nVivienne Ong, Local Governance Specialist, Christchurch, New Zealand\n\n{{STORY}}\nhttps://res.cloudinary.com/mindvalley/image/fetch/f_auto,q_auto,w_400,h_400,c_fill,dpr_1.7/https://storage.googleapis.com/mv-stories/34478/Red%20queen5.jpg\n**\\\"This program is game-changing\\\"**\nCesar Pinto, Food Chemist, Schorndorf, Germany\n\n{{STORY}}\nhttps://res.cloudinary.com/mindvalley/image/fetch/f_auto,q_auto,w_400,h_400,c_fill,dpr_1.7/https://storage.googleapis.com/mv-stories/32424/Indrani%20Animal%20Reiki%20Shamanic%20Healer_Hi%20Res.jpg\n**\\\"Thanks to the quest, something incredible happened--a sudden and exponential growth in clients\\\"**\nIndrani, Animal Care Giver, Sylhet, Bangladesh\n\n{{STORY}}\nhttps://res.cloudinary.com/mindvalley/image/fetch/f_auto,q_auto,w_400,h_400,c_fill,dpr_1.7/https://storage.googleapis.com/mv-stories/24905/IMG_3173.jpeg\n**\\\"My days are smooth and flow with ease\\\"**\nNancy Morgan-McCord, Entrepreneur, San Antonio, United States\n\n**Do not let the streak break now.**\n\n**[Keep Building](https://www.mindvalley.com/app)**\n\nThe Mindvalley Team\n\nP.S. Stopping now would mean walking away from the compound interest just as it starts to pay. You know how compound interest works. Stay in the market."
}

});
